name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          template: "@kitty-mocha"
          setup_community_templates: "SDAlex66/SDAlex66@main:kitty-mocha+trust"
          filename: github-metrics.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://www.alextula.com
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
