name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          template: "@metrics-template"

          
          setup_community_templates: "SDAlex66/SDAlex66@main:metrics-template+trust"
          
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://alextula.com
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
